config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'contact', to: 'pages#contact'

  resources :categories
  resources :articles do
    member do
      patch "/downvote", to: 'articles#downvote'
      patch "/upvote", to: 'articles#upvote'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
  has_one_attached :photo
  # accepts_nested_attributes_for :category

  validates :name, presence: true
  validates :photo, presence: true
  validates :category, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles, dependent: :destroy

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index]
  before_action :set_article, only: [:edit, :update, :destroy, :downvote, :upvote]

  def new
    @article = Article.new
    @categories = Category.all
  end

  def create
    @article = Article.new(article_params)
    @article.category = Category.find(params[:article][:category_id])
    @article.star = params[:article][:star] == "1" ? true : false
    if @article.save
      flash[:notice] = "Nouvelle création ajoutée !"
      redirect_to articles_path(anchor: "article-#{@article.id}")
    else
      render :new
    end
  end

  def index
    @articles = Article.all
    @categories = Category.all
    @category = Category.new
  end

  def edit
    @categories = Category.all
  end

  def update
    @article.update(article_params)
    flash[:notice] = "La créations #{@article.name} a été modifié."
    redirect_to articles_path
  end

  def destroy
    @article.photo.purge
    @article.destroy
    flash[:alert] = "Tu viens de supprimer #{@article.name}."
    redirect_to articles_path
  end

  def downvote
    @article.star = false
    @article.save
    flash[:alert] = "#{@article.name} ne fait plus parti des favoris."
    redirect_to articles_path(anchor: "article-#{@article.id}")
  end

  def upvote
    if Article.where(star: true).count >= 9
      flash[:alert] = "Désolée papou, tu as déjà 9 favoris."
      redirect_to articles_path
    else
      @article.star = true
      @article.save
      flash[:notice] = "C'est bon ! #{@article.name} est dans les favoris."
      redirect_to articles_path(anchor: "article-#{@article.id}")
    end
  end

  private

  def article_params
    params.require(:article).permit(:name, :description, :star, :photo)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:destroy]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "La catégorie #{@category.name} a bien été créée."
      redirect_to articles_path
    else
      render :new
    end
  end

  def destroy
    @category.destroy
    flash[:alert] = "La catégorie #{@category.name.downcase} a été supprimée ainsi que toutes les oeuvres associées."
    redirect_to articles_path
  end
  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :contact ]

  def home
    @star_articles = Article.where(star: true)
    @selected_categories = @star_articles.map { |article| article.category}.uniq
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/articles/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <%= simple_form_for @article do |f| %>
        <div class="form-row">
          <div class="col-12 col-md-6 form-group">
            <%= f.input :name, label: "Nom de l'oeuvre", placeholder: "Fleur rose" %>
          </div>
          <div class="col-12 col-md-6 form-group">
            <%= f.input :category_id, label: "Catégorie", as: :select, collection: @categories, selected: 1 %>
          </div>
        </div>

<!--         <div class="new-category">
          <div id="new-category-link">
            <p>ajouter une catégorie</p>
          </div>
          <div id="new-category-form" class="d-none">
            <#%= f.simple_fields_for :category do |m| %>
              <#%= m.input :name, label: "Nom de la nouvelle catégorie" %>
            <#% end %>
          </div>
        </div> -->
        <div class="form-group">
          <%= f.input :description, label: "Description", placeholder: "Jolie fleur en verre avec pétales en dégradé de rose" %>
        </div>
        <div class="form-group">
          <%= f.input :star, label:"Classer en favori ?", as: :boolean %>
        </div>
        <div class="form-group">
          <%= f.input :photo, as: :file, input_html: { class: 'd-none', id: 'photo-input'}, label_html: { class: 'upload-photo'}, label: '📷 Ajoute une photo' %>
          <%= image_tag "", width: 300, class: "d-none", id: "photo-preview" %>
        </div>

        <%= f.submit "Enregistrer", class: "button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<head>
  <meta name="turbolinks-visit-control" content="reload">
</head>

<div id="content" class="site-content">
  <div class="content-1330 center-relative">
    <div class="button-group filters-button-group pt-0">
      <% unless @categories.empty? %>
        <div class="button is-checked" data-filter="*">Tout</div>
      <% end %>
      <% @categories.each do |category| %>
        <div class="button text" data-filter=".<%= category.name %>">
          <%= category.name.capitalize %>
          <% if user_signed_in? %>
            <%= link_to category_path(category),
                        method: :delete,
                        remote: true,
                        data: { confirm: "En supprimant cette catégorie tu supprimeras toutes les oeuvres qui en font partie. Veux-tu continuer ?"} do %>
              <span class="delete-category-icon"><i class="far fa-times-circle"></i></span>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <% if user_signed_in? %>
        <div id="new-form">
          <% if @categories.empty? %>
            <span id="new-form-link">
              <p><small><i class="fas fa-plus mr-2"></i>ajoute ta première catégorie</small></p>
            </span>
          <% else %>
            <span id="new-form-link"><p><small>ajouter une catégorie</small></p></span>
          <% end %>
          <div id="new-form-input" class="d-none">
            <%= simple_form_for([@category], remote: true) do |m| %>
              <%= m.input :name, label: "Nom de la nouvelle catégorie", placeholder: "Verre, argile ..." %>
              <%= m.submit "Enregistrer", class: "form-button" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="grid" id="portfolio">
      <div class="grid-sizer"></div>

        <% if user_signed_in? %>
          <div class="grid-item element-item p_one_third new-article-item">
            <div class="item">
              <%= image_tag "https://images.unsplash.com/photo-1575578285291-905e55d5a789?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80", height: 300, width: 400, crop: :fit %>
              <%= link_to new_article_path do %>
                <div class="new-article-overlay">
                  <i class="fas fa-plus"></i>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>

        <% @articles.order('articles.created_at DESC').each do |article| %>
          <div id="article-<%= article.id %>" class="grid-item element-item p_one_third <%= article.category.name %>">

            <div class="item position-relative">
              <%= cl_image_tag article.photo.key, height: 400, width: 400, crop: :thumb, alt: "article.name" %>

              <% if user_signed_in? %>
                <div class="edit-article-zone">
                  <div class="delete-article-icon">
                    <%= link_to article_path(article),
                                  method: :delete,
                                  remote: true,
                                  data: { confirm: "Es-tu sûr de vouloir supprimer cette oeuvre ?"} do %>
                      <i class="far fa-times-circle"></i>
                    <% end %>
                  </div>
                  <div class="star-article-icons">
                    <p><small>
                      <% if article.star? %>
                        <%= link_to downvote_article_path(article), method: :patch, remote: true do %>
                          <i class="fas fa-star"></i>
                        <% end %>
                      <% else %>
                        <%= link_to upvote_article_path(article), method: :patch, remote: true do %>
                          <i class="far fa-star"></i>
                        <% end %>
                      <% end %>
                    </small></p>
                  </div>
                  <div class="edit-article-text">
                    <div class="d-flex align-items-start">
                      <p><%= article.name.upcase %></p>
                      <span class="ml-3"><small>
                        <%= link_to edit_article_path(article) do %>
                          <i class="far fa-edit"></i>
                        <% end  %>
                      </small></span>
                    </div>

                    <p><small><%= article.category.name %></small></p>
                    <p><small><%= article.description %></small></p>
                  </div>
                </div>
              <% else %>
                <div class="portfolio-text-holder">
                  <p><%= article.name.upcase %></p>
                  <p><%= article.description %></p>
                </div>
              <% end %>

            </div>
          </div>
        <% end %>

    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <%= simple_form_for([@article], remote: true) do |f| %>
        <div class="form-row">
          <div class="col-12 col-md-6 form-group">
            <%= f.input :name, label: "Nom de l'oeuvre", placeholder: "Fleur rose" %>
          </div>
          <div class="col-12 col-md-6 form-group">
            <%= f.input :category_id, label: "Catégorie", as: :select, collection: @categories, selected: 1 %>
          </div>
        </div>
        <div class="form-group">
          <%= f.input :description, label: "Description", placeholder: "Jolie fleur en verre avec pétales en dégradé de rose" %>
        </div>
        <div class="form-group">
          <%= f.input :star, label:"Classer en favori ?", as: :boolean %>
        </div>
        <div class="form-group">
          <%= f.input :photo, as: :file, input_html: { class: 'd-none', id: 'photo-input'}, label_html: { class: 'upload-photo'}, label: '📷 Ajoute une photo' %>
          <%= image_tag "", width: 300, class: "d-none", id: "photo-preview" %>
        </div>
        <%= f.submit "Enregistrer", class: "form-button" %>
      <% end %>

      <small><%= link_to "Annuler", articles_path  %></small>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag 'logo-remi-vert.png' %>
  </head>

  <body>
    <div class="body-wrapper">
      <%= render 'shared/flashes' %>
      <%= render 'shared/navbar' %>

      <%= yield %>

      <%= render 'shared/footer' %>
      <%= render 'shared/login' %>
    </div>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="content-1330 center-relative">
  <div class="typeform-widget" data-url="https://philippine648702.typeform.com/to/Mpt9Ns" style="width: 100%; height: 500px;">

  </div>
  <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script>
  <div style="font-family: Sans-Serif;font-size: 12px;color: #999;opacity: 0.5; padding-top: 5px;"> powered by <a href="https://admin.typeform.com/signup?utm_campaign=Mpt9Ns&utm_source=typeform.com-01DDQHNYHY23B79KQ67Y61Q9GH-free&utm_medium=typeform&utm_content=typeform-embedded-poweredbytypeform&utm_term=EN" style="color: #999" target="_blank">Typeform</a>
  </div>
</div>

app/views/pages/home.html.erb
<div id="content" class="site-content">
  <article>
    <div class="content-1330 center-relative">
      <div class="main-description">
        <h1>Rémi Créations</h1> propose la réalisation de pièces uniques en verre et en argile. Des oeuvres en vitrail ou sculptées, réalisées à la main et destinées à la décoration d'intérieur.
      </div>

      <div class="button-group filters-button-group">
        <div class="button is-checked" data-filter="*">Tout</div>
        <% @selected_categories.each do |category| %>
          <div class="button" data-filter=".<%= category.name %>">
            <%= category.name.capitalize %>
          </div>
        <% end %>
      </div>


      <div class="grid" id="portfolio">
        <div class="grid-sizer"></div>

          <% @star_articles.order('articles.created_at DESC').each do |article| %>

            <div class="grid-item element-item p_one_third <%= article.category.name %>">
              <div class="item">
                <%= cl_image_tag article.photo.key, crop: :fit, alt: "article.name" %>
                <div class="portfolio-text-holder">
                  <p><%= article.name.upcase %></p>
                  <p><small><%= article.description %></small></p>
                </div>
              </div>
            </div>

          <% end %>
<!-- PROJETS -->

      </div>

      <div class="home-description">
        <div class="one_half">
          <p>
            <strong>L'histoire</strong>
            <br>
            Rémi a un parcours atypique dans le domaine de l'art. Il n'a pas suivi de formation comme la plupart des artisans verriers.
          </p>
          <p>Autodidacte, c'est dans l'atelier de sa maison qu'il s'essaie à l'art du vitrail. Il chauffe, casse et recommence jusqu'à la réalisation de sa première oeuvre. De l'art floral, de l'art contemporain, des pieds de table, il donne à cette matière toutes les formes.</p>
        </div>
        <div class="one_half last">
          <p>
            <strong>Les créations</strong>
            <br>
            Toujours une idée en tête, il ne se limite pas au travail du verre. Dans son atelier on peut trouver de l'argile, de la céramique, du bois et de l'epoxy. Ses sources d'inspiration sont nombreuses.
          </p>
          <p>&nbsp;</p>
          <div class="text-left">
            <%= link_to "Contact", contact_path, class: "button" %>
          </div>
        </div>
      </div>
    </div>
  </article>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="content-1330 center-relative">
    <div class="footer-center">
      <%= link_to image_tag("logo-remi-vert.png", width:"150px", alt:"Logo Rémi Créations"), root_path %>
    </div>
  </div>
</footer>

app/views/shared/_login.html.erb
<div class="login">
  <% if user_signed_in? %>
    <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "log-link" %>
  <% else %>
    <%= link_to "Se connecter", new_user_session_path, class: "log-link" %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="content-1330 header-holder center-relative">
  <div class="header-logo left">
    <%= link_to image_tag("logo-remi-vert.png", width:"200px", alt:"Logo Rémi Créations"), root_path %>
  </div>

  <div class="header-menu right">
    <nav id="header-main-menu">
      <ul class="main-menu">
        <li class="<%= 'active' if current_page?(root_path) %>">
          <%= link_to "Accueil", root_path %>
        </li>
        <li class="<%= 'active' if current_page?(articles_path) %>">
          <%= link_to "Collections", articles_path %>
        </li>
        <li class="<%= 'active' if current_page?(contact_path) %>">
          <%= link_to "Contact", contact_path %>
        </li>
      </ul>
    </nav>
  </div>
</div>